package cc.funkemunky.api.utils.blockbox.impl;

import cc.funkemunky.api.utils.BoundingBox;
import org.bukkit.Bukkit;
import org.bukkit.Material;

import java.io.UnsupportedEncodingException;
import java.util.*;

public class BoundingBoxes {
    private Map<Material, RegularBox> blockBoxes = new HashMap<>();

    public void addBox() {
        List<String> strings = new ArrayList<>();


        blockBoxes.put(Material.AIR, new RegularBox(Material.AIR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STONE, new RegularBox(Material.STONE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.GRASS, new RegularBox(Material.GRASS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DIRT, new RegularBox(Material.DIRT, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.COBBLESTONE, new RegularBox(Material.COBBLESTONE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WOOD, new RegularBox(Material.WOOD, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SAPLING, new RegularBox(Material.SAPLING, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BEDROCK, new RegularBox(Material.BEDROCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WATER, new RegularBox(Material.WATER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STATIONARY_WATER, new RegularBox(Material.STATIONARY_WATER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LAVA, new RegularBox(Material.LAVA, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STATIONARY_LAVA, new RegularBox(Material.STATIONARY_LAVA, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SAND, new RegularBox(Material.SAND, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.GRAVEL, new RegularBox(Material.GRAVEL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.GOLD_ORE, new RegularBox(Material.GOLD_ORE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.IRON_ORE, new RegularBox(Material.IRON_ORE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.COAL_ORE, new RegularBox(Material.COAL_ORE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LOG, new RegularBox(Material.LOG, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LEAVES, new RegularBox(Material.LEAVES, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SPONGE, new RegularBox(Material.SPONGE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.GLASS, new RegularBox(Material.GLASS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LAPIS_ORE, new RegularBox(Material.LAPIS_ORE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LAPIS_BLOCK, new RegularBox(Material.LAPIS_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DISPENSER, new RegularBox(Material.DISPENSER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SANDSTONE, new RegularBox(Material.SANDSTONE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.NOTE_BLOCK, new RegularBox(Material.NOTE_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BED_BLOCK, new RegularBox(Material.BED_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.POWERED_RAIL, new RegularBox(Material.POWERED_RAIL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DETECTOR_RAIL, new RegularBox(Material.DETECTOR_RAIL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.PISTON_STICKY_BASE, new RegularBox(Material.PISTON_STICKY_BASE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WEB, new RegularBox(Material.WEB, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LONG_GRASS, new RegularBox(Material.LONG_GRASS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DEAD_BUSH, new RegularBox(Material.DEAD_BUSH, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.PISTON_BASE, new RegularBox(Material.PISTON_BASE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.PISTON_EXTENSION, new RegularBox(Material.PISTON_EXTENSION, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WOOL, new RegularBox(Material.WOOL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.PISTON_MOVING_PIECE, new RegularBox(Material.PISTON_MOVING_PIECE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.YELLOW_FLOWER, new RegularBox(Material.YELLOW_FLOWER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.RED_ROSE, new RegularBox(Material.RED_ROSE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BROWN_MUSHROOM, new RegularBox(Material.BROWN_MUSHROOM, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.RED_MUSHROOM, new RegularBox(Material.RED_MUSHROOM, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.GOLD_BLOCK, new RegularBox(Material.GOLD_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.IRON_BLOCK, new RegularBox(Material.IRON_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DOUBLE_STEP, new RegularBox(Material.DOUBLE_STEP, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STEP, new RegularBox(Material.STEP, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BRICK, new RegularBox(Material.BRICK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.TNT, new RegularBox(Material.TNT, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BOOKSHELF, new RegularBox(Material.BOOKSHELF, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.MOSSY_COBBLESTONE, new RegularBox(Material.MOSSY_COBBLESTONE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.OBSIDIAN, new RegularBox(Material.OBSIDIAN, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.TORCH, new RegularBox(Material.TORCH, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.FIRE, new RegularBox(Material.FIRE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.MOB_SPAWNER, new RegularBox(Material.MOB_SPAWNER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WOOD_STAIRS, new RegularBox(Material.WOOD_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.CHEST, new RegularBox(Material.CHEST, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.REDSTONE_WIRE, new RegularBox(Material.REDSTONE_WIRE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DIAMOND_ORE, new RegularBox(Material.DIAMOND_ORE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DIAMOND_BLOCK, new RegularBox(Material.DIAMOND_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WORKBENCH, new RegularBox(Material.WORKBENCH, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.CROPS, new RegularBox(Material.CROPS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SOIL, new RegularBox(Material.SOIL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.FURNACE, new RegularBox(Material.FURNACE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BURNING_FURNACE, new RegularBox(Material.BURNING_FURNACE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SIGN_POST, new RegularBox(Material.SIGN_POST, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WOODEN_DOOR, new RegularBox(Material.WOODEN_DOOR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LADDER, new RegularBox(Material.LADDER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.RAILS, new RegularBox(Material.RAILS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.COBBLESTONE_STAIRS, new RegularBox(Material.COBBLESTONE_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WALL_SIGN, new RegularBox(Material.WALL_SIGN, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LEVER, new RegularBox(Material.LEVER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STONE_PLATE, new RegularBox(Material.STONE_PLATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.IRON_DOOR_BLOCK, new RegularBox(Material.IRON_DOOR_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WOOD_PLATE, new RegularBox(Material.WOOD_PLATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.REDSTONE_ORE, new RegularBox(Material.REDSTONE_ORE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.GLOWING_REDSTONE_ORE, new RegularBox(Material.GLOWING_REDSTONE_ORE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.REDSTONE_TORCH_OFF, new RegularBox(Material.REDSTONE_TORCH_OFF, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.REDSTONE_TORCH_ON, new RegularBox(Material.REDSTONE_TORCH_ON, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STONE_BUTTON, new RegularBox(Material.STONE_BUTTON, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SNOW, new RegularBox(Material.SNOW, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ICE, new RegularBox(Material.ICE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SNOW_BLOCK, new RegularBox(Material.SNOW_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.CACTUS, new RegularBox(Material.CACTUS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.CLAY, new RegularBox(Material.CLAY, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SUGAR_CANE_BLOCK, new RegularBox(Material.SUGAR_CANE_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.JUKEBOX, new RegularBox(Material.JUKEBOX, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.FENCE, new RegularBox(Material.FENCE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.PUMPKIN, new RegularBox(Material.PUMPKIN, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.NETHERRACK, new RegularBox(Material.NETHERRACK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SOUL_SAND, new RegularBox(Material.SOUL_SAND, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.GLOWSTONE, new RegularBox(Material.GLOWSTONE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.PORTAL, new RegularBox(Material.PORTAL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.JACK_O_LANTERN, new RegularBox(Material.JACK_O_LANTERN, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.CAKE_BLOCK, new RegularBox(Material.CAKE_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DIODE_BLOCK_OFF, new RegularBox(Material.DIODE_BLOCK_OFF, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DIODE_BLOCK_ON, new RegularBox(Material.DIODE_BLOCK_ON, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STAINED_GLASS, new RegularBox(Material.STAINED_GLASS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.TRAP_DOOR, new RegularBox(Material.TRAP_DOOR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.MONSTER_EGGS, new RegularBox(Material.MONSTER_EGGS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SMOOTH_BRICK, new RegularBox(Material.SMOOTH_BRICK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.HUGE_MUSHROOM_1, new RegularBox(Material.HUGE_MUSHROOM_1, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.HUGE_MUSHROOM_2, new RegularBox(Material.HUGE_MUSHROOM_2, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.IRON_FENCE, new RegularBox(Material.IRON_FENCE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.THIN_GLASS, new RegularBox(Material.THIN_GLASS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.MELON_BLOCK, new RegularBox(Material.MELON_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.PUMPKIN_STEM, new RegularBox(Material.PUMPKIN_STEM, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.MELON_STEM, new RegularBox(Material.MELON_STEM, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.VINE, new RegularBox(Material.VINE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.FENCE_GATE, new RegularBox(Material.FENCE_GATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BRICK_STAIRS, new RegularBox(Material.BRICK_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SMOOTH_STAIRS, new RegularBox(Material.SMOOTH_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.MYCEL, new RegularBox(Material.MYCEL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WATER_LILY, new RegularBox(Material.WATER_LILY, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.NETHER_BRICK, new RegularBox(Material.NETHER_BRICK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.NETHER_FENCE, new RegularBox(Material.NETHER_FENCE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.NETHER_BRICK_STAIRS, new RegularBox(Material.NETHER_BRICK_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.NETHER_WARTS, new RegularBox(Material.NETHER_WARTS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ENCHANTMENT_TABLE, new RegularBox(Material.ENCHANTMENT_TABLE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BREWING_STAND, new RegularBox(Material.BREWING_STAND, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.CAULDRON, new RegularBox(Material.CAULDRON, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ENDER_PORTAL, new RegularBox(Material.ENDER_PORTAL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ENDER_PORTAL_FRAME, new RegularBox(Material.ENDER_PORTAL_FRAME, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ENDER_STONE, new RegularBox(Material.ENDER_STONE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DRAGON_EGG, new RegularBox(Material.DRAGON_EGG, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.REDSTONE_LAMP_OFF, new RegularBox(Material.REDSTONE_LAMP_OFF, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.REDSTONE_LAMP_ON, new RegularBox(Material.REDSTONE_LAMP_ON, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WOOD_DOUBLE_STEP, new RegularBox(Material.WOOD_DOUBLE_STEP, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WOOD_STEP, new RegularBox(Material.WOOD_STEP, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.COCOA, new RegularBox(Material.COCOA, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SANDSTONE_STAIRS, new RegularBox(Material.SANDSTONE_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.EMERALD_ORE, new RegularBox(Material.EMERALD_ORE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ENDER_CHEST, new RegularBox(Material.ENDER_CHEST, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.TRIPWIRE_HOOK, new RegularBox(Material.TRIPWIRE_HOOK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.TRIPWIRE, new RegularBox(Material.TRIPWIRE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.EMERALD_BLOCK, new RegularBox(Material.EMERALD_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SPRUCE_WOOD_STAIRS, new RegularBox(Material.SPRUCE_WOOD_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BIRCH_WOOD_STAIRS, new RegularBox(Material.BIRCH_WOOD_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.JUNGLE_WOOD_STAIRS, new RegularBox(Material.JUNGLE_WOOD_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.COMMAND, new RegularBox(Material.COMMAND, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BEACON, new RegularBox(Material.BEACON, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.COBBLE_WALL, new RegularBox(Material.COBBLE_WALL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.FLOWER_POT, new RegularBox(Material.FLOWER_POT, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.CARROT, new RegularBox(Material.CARROT, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.POTATO, new RegularBox(Material.POTATO, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WOOD_BUTTON, new RegularBox(Material.WOOD_BUTTON, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SKULL, new RegularBox(Material.SKULL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ANVIL, new RegularBox(Material.ANVIL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.TRAPPED_CHEST, new RegularBox(Material.TRAPPED_CHEST, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.GOLD_PLATE, new RegularBox(Material.GOLD_PLATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.IRON_PLATE, new RegularBox(Material.IRON_PLATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.REDSTONE_COMPARATOR_OFF, new RegularBox(Material.REDSTONE_COMPARATOR_OFF, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.REDSTONE_COMPARATOR_ON, new RegularBox(Material.REDSTONE_COMPARATOR_ON, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DAYLIGHT_DETECTOR, new RegularBox(Material.DAYLIGHT_DETECTOR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.REDSTONE_BLOCK, new RegularBox(Material.REDSTONE_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.QUARTZ_ORE, new RegularBox(Material.QUARTZ_ORE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.HOPPER, new RegularBox(Material.HOPPER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.QUARTZ_BLOCK, new RegularBox(Material.QUARTZ_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.QUARTZ_STAIRS, new RegularBox(Material.QUARTZ_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ACTIVATOR_RAIL, new RegularBox(Material.ACTIVATOR_RAIL, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DROPPER, new RegularBox(Material.DROPPER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STAINED_CLAY, new RegularBox(Material.STAINED_CLAY, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STAINED_GLASS_PANE, new RegularBox(Material.STAINED_GLASS_PANE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LEAVES_2, new RegularBox(Material.LEAVES_2, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.LOG_2, new RegularBox(Material.LOG_2, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ACACIA_STAIRS, new RegularBox(Material.ACACIA_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DARK_OAK_STAIRS, new RegularBox(Material.DARK_OAK_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SLIME_BLOCK, new RegularBox(Material.SLIME_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BARRIER, new RegularBox(Material.BARRIER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.IRON_TRAPDOOR, new RegularBox(Material.IRON_TRAPDOOR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.PRISMARINE, new RegularBox(Material.PRISMARINE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SEA_LANTERN, new RegularBox(Material.SEA_LANTERN, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.HAY_BLOCK, new RegularBox(Material.HAY_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.CARPET, new RegularBox(Material.CARPET, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.HARD_CLAY, new RegularBox(Material.HARD_CLAY, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.COAL_BLOCK, new RegularBox(Material.COAL_BLOCK, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.PACKED_ICE, new RegularBox(Material.PACKED_ICE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DOUBLE_PLANT, new RegularBox(Material.DOUBLE_PLANT, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DAYLIGHT_DETECTOR_INVERTED, new RegularBox(Material.DAYLIGHT_DETECTOR_INVERTED, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.RED_SANDSTONE, new RegularBox(Material.RED_SANDSTONE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.RED_SANDSTONE_STAIRS, new RegularBox(Material.RED_SANDSTONE_STAIRS, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DOUBLE_STONE_SLAB2, new RegularBox(Material.DOUBLE_STONE_SLAB2, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STONE_SLAB2, new RegularBox(Material.STONE_SLAB2, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SPRUCE_FENCE_GATE, new RegularBox(Material.SPRUCE_FENCE_GATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BIRCH_FENCE_GATE, new RegularBox(Material.BIRCH_FENCE_GATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.JUNGLE_FENCE_GATE, new RegularBox(Material.JUNGLE_FENCE_GATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DARK_OAK_FENCE_GATE, new RegularBox(Material.DARK_OAK_FENCE_GATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ACACIA_FENCE_GATE, new RegularBox(Material.ACACIA_FENCE_GATE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SPRUCE_FENCE, new RegularBox(Material.SPRUCE_FENCE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BIRCH_FENCE, new RegularBox(Material.BIRCH_FENCE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.JUNGLE_FENCE, new RegularBox(Material.JUNGLE_FENCE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DARK_OAK_FENCE, new RegularBox(Material.DARK_OAK_FENCE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ACACIA_FENCE, new RegularBox(Material.ACACIA_FENCE, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.SPRUCE_DOOR, new RegularBox(Material.SPRUCE_DOOR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.BIRCH_DOOR, new RegularBox(Material.BIRCH_DOOR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.JUNGLE_DOOR, new RegularBox(Material.JUNGLE_DOOR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.ACACIA_DOOR, new RegularBox(Material.ACACIA_DOOR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.DARK_OAK_DOOR, new RegularBox(Material.DARK_OAK_DOOR, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.STANDING_BANNER, new RegularBox(Material.STANDING_BANNER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        blockBoxes.put(Material.WALL_BANNER, new RegularBox(Material.WALL_BANNER, new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));
        Arrays.stream(Material.values()).filter(Material::isBlock).forEach(material -> {
            strings.add("blockBoxes.put(Material." + material.toString() + ", new RegularBox(Material." + material.toString() + ", new BoundingBox(1f, 1f, 1f, 1f, 1f, 1f)));");
        });

        StringBuilder bodyBuilder = new StringBuilder();

        strings.forEach(line -> bodyBuilder.append(line).append("\n"));
    }
}
